services:
  app1:
    image: "ramz001/haproxy-test:latest"
    container_name: app1
    environment:
      - APP_NAME=App-One
    ports:
      - "3020:3000"

  app2:
    image: "ramz001/haproxy-test:latest"
    container_name: app2
    environment:
      - APP_NAME=App-Two
    ports:
      - "3030:3000"

  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    ports:
      - "8080:80"   # map host 8080 to container 80
    volumes:
      - ./configs/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
